include: package:flutter_lints/flutter.yaml
formatter: 
  trailing_commas: preserve
linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    package_names: true
    constant_identifier_names: true
    unawaited_futures: true
    avoid_void_async: true
    discarded_futures: true
    exhaustive_cases: true
analyzer:
  exclude:
    - packages/**
